spring:
  datasource:
    url: jdbc:h2:mem:recruit;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: false
    open-in-view: true
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 8080
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
